# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - nix
    - proot
  jobs:
    pre_install:
      - mkdir -p ~/.nix ~/.config/nix
      - echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
      - proot -b ~/.nix:/nix /bin/sh -c "nix build -L .#optionsDoc && cp -v result docs/options.md"

sphinx:
   configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
   install:
   - requirements: docs/requirements.txt
